name: Bug report
description: Report an application bug
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps
      placeholder: |
        1. Open CO33-Pictos.html
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: "Chrome 132 / Firefox 133 / Edge 132..."
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Windows 11, macOS 15, Ubuntu 24.04..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
      description: Optional
    validations:
      required: false
